name: Build And Release
# Build and Release a new version of Pyspark Framework

on:
  workflow_dispatch:
    branches: [main]
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]

jobs:
  create-release-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project using Python - ${{matrix.python-version}}
        uses: actions/checkout@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies using pip
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: running flake 8 to adhere python coding standard
        run: flake8 src #--ignore=E501, 265,

      - name: running Bandit to check vulnerability
        run: bandit -r src

      - name: running unittest with coverage report
        run: python -m coverage run -m unittest discover -s test -p "*_test.py" && python -m coverage report && 
              python -m coverage html

      - name: running unittest with coverage report
        run: python -m coverage run -m unittest discover -s test -p "*_test.py" && python -m coverage report &&
          python -m coverage html



